### ISSUE TITLE
What license is this code released under?

### ISSUE THREAD

**Issue by jjneely** [jssjr/libwhisper#3]
Missing license file.

**Comment by jssjr** [comment]
What license would you like? This was just a fun project to refresh my C skills a bit. There is a _ton_ that still needs to be implemented.

**Comment by jjneely** [comment]
MIT / BSD?

Yeah, let's just say I'm considering similar routes, and would love to start from even partial work rather than implementing from ground zero.

I understand that this code may harm my computer.  ;-)

**Comment by jssjr** [comment]
I added a MIT license to it. I'm not sure if you want to fork the repo or PR things here. I'll make you a contributor so you can do either.
